// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.

package cli

import (
	"github.com/spf13/cobra"
	"github.com/straddle-build/straddle-cli/internal/surface"
)

func init() {
	registerGeneratedEndpoint("accounts.create", newAccountsCreateCmd)
	registerSurface(surface.Surface{
		Endpoint:    "accounts.create",
		OperationID: "createAccount",
		Method:      "POST",
		Path:        "/v1/accounts",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "idempotency-key",
				In:          surface.InHeader,
				Key:         "Idempotency-Key",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated key for an idempotent request.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
			{
				Name:        "access-level",
				In:          surface.InBody,
				Key:         "/access_level",
				Kind:        surface.KindString,
				Required:    true,
				Enum:        []string{"standard", "managed"},
				Description: "The account access level.",
			},
			{
				Name:        "account-type",
				In:          surface.InBody,
				Key:         "/account_type",
				Kind:        surface.KindString,
				Required:    true,
				Enum:        []string{"business"},
				Description: "Account type.",
			},
			{
				Name:        "business-profile-address-city",
				In:          surface.InBody,
				Key:         "/business_profile/address/city",
				Kind:        surface.KindString,
				Description: "City, district, suburb, town, or village.",
			},
			{
				Name:        "business-profile-address-country",
				In:          surface.InBody,
				Key:         "/business_profile/address/country",
				Kind:        surface.KindString,
				Description: "Two-letter ISO 3166-1 country code.",
			},
			{
				Name:        "business-profile-address-line1",
				In:          surface.InBody,
				Key:         "/business_profile/address/line1",
				Kind:        surface.KindString,
				Description: "Primary address line, such as a street address or PO Box.",
			},
			{
				Name:        "business-profile-address-line2",
				In:          surface.InBody,
				Key:         "/business_profile/address/line2",
				Kind:        surface.KindString,
				Description: "Secondary address line, such as an apartment, suite, unit, or building.",
			},
			{
				Name:        "business-profile-address-postal-code",
				In:          surface.InBody,
				Key:         "/business_profile/address/postal_code",
				Kind:        surface.KindString,
				Description: "Postal or ZIP code.",
			},
			{
				Name:        "business-profile-address-state",
				In:          surface.InBody,
				Key:         "/business_profile/address/state",
				Kind:        surface.KindString,
				Description: "Two-letter state code.",
			},
			{
				Name:        "business-profile-description",
				In:          surface.InBody,
				Key:         "/business_profile/description",
				Kind:        surface.KindString,
				Description: "Description of the business and its products or services.",
			},
			{
				Name:        "business-profile-industry-category",
				In:          surface.InBody,
				Key:         "/business_profile/industry/category",
				Kind:        surface.KindString,
				Description: "Industry category.",
			},
			{
				Name:        "business-profile-industry-mcc",
				In:          surface.InBody,
				Key:         "/business_profile/industry/mcc",
				Kind:        surface.KindString,
				Description: "Merchant category code (MCC) that best describes the business.",
			},
			{
				Name:        "business-profile-industry-sector",
				In:          surface.InBody,
				Key:         "/business_profile/industry/sector",
				Kind:        surface.KindString,
				Description: "Business sector.",
			},
			{
				Name:        "business-profile-legal-name",
				In:          surface.InBody,
				Key:         "/business_profile/legal_name",
				Kind:        surface.KindString,
				Description: "The official registered name of the business.",
			},
			{
				Name:        "business-profile-name",
				In:          surface.InBody,
				Key:         "/business_profile/name",
				Kind:        surface.KindString,
				Required:    true,
				Description: "The operating or trade name of the business.",
			},
			{
				Name:        "business-profile-phone",
				In:          surface.InBody,
				Key:         "/business_profile/phone",
				Kind:        surface.KindString,
				Description: "Primary business phone number in E.164 format.",
			},
			{
				Name:        "business-profile-support-channels-email",
				In:          surface.InBody,
				Key:         "/business_profile/support_channels/email",
				Kind:        surface.KindString,
				Description: "Email address for customer support.",
				Format:      "email",
			},
			{
				Name:        "business-profile-support-channels-phone",
				In:          surface.InBody,
				Key:         "/business_profile/support_channels/phone",
				Kind:        surface.KindString,
				Description: "Customer support phone number in E.164 format.",
			},
			{
				Name:        "business-profile-support-channels-url",
				In:          surface.InBody,
				Key:         "/business_profile/support_channels/url",
				Kind:        surface.KindString,
				Description: "URL of the business's customer support page or contact form.",
				Format:      "uri",
			},
			{
				Name:        "business-profile-tax-id",
				In:          surface.InBody,
				Key:         "/business_profile/tax_id",
				Kind:        surface.KindString,
				Description: "Business tax identification number, such as a US Employer Identification Number (EIN).",
			},
			{
				Name:        "business-profile-use-case",
				In:          surface.InBody,
				Key:         "/business_profile/use_case",
				Kind:        surface.KindString,
				Description: "How the business plans to use Straddle.",
			},
			{
				Name:        "business-profile-website",
				In:          surface.InBody,
				Key:         "/business_profile/website",
				Kind:        surface.KindString,
				Required:    true,
				Description: "URL of the business's primary website.",
				Format:      "uri",
			},
			{
				Name:        "external-id",
				In:          surface.InBody,
				Key:         "/external_id",
				Kind:        surface.KindString,
				Description: "Your unique ID for the account.",
			},
			{
				Name:        "metadata",
				In:          surface.InBody,
				Key:         "/metadata",
				Kind:        surface.KindJSON,
				Description: "Up to 20 user-defined key-value pairs.",
			},
			{
				Name:        "organization-id",
				In:          surface.InBody,
				Key:         "/organization_id",
				Kind:        surface.KindString,
				Required:    true,
				Description: "ID of the organization that will own the account.",
				Format:      "uuid",
			},
		},
		HasBody:              true,
		BodyRequired:         true,
		AcceptsAccountHeader: false,
		ReadOnly:             false,
	})
}

func newAccountsCreateCmd(flags *rootFlags) *cobra.Command {
	s := surface.Surface{
		Endpoint:    "accounts.create",
		OperationID: "createAccount",
		Method:      "POST",
		Path:        "/v1/accounts",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "idempotency-key",
				In:          surface.InHeader,
				Key:         "Idempotency-Key",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated key for an idempotent request.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
			{
				Name:        "access-level",
				In:          surface.InBody,
				Key:         "/access_level",
				Kind:        surface.KindString,
				Required:    true,
				Enum:        []string{"standard", "managed"},
				Description: "The account access level.",
			},
			{
				Name:        "account-type",
				In:          surface.InBody,
				Key:         "/account_type",
				Kind:        surface.KindString,
				Required:    true,
				Enum:        []string{"business"},
				Description: "Account type.",
			},
			{
				Name:        "business-profile-address-city",
				In:          surface.InBody,
				Key:         "/business_profile/address/city",
				Kind:        surface.KindString,
				Description: "City, district, suburb, town, or village.",
			},
			{
				Name:        "business-profile-address-country",
				In:          surface.InBody,
				Key:         "/business_profile/address/country",
				Kind:        surface.KindString,
				Description: "Two-letter ISO 3166-1 country code.",
			},
			{
				Name:        "business-profile-address-line1",
				In:          surface.InBody,
				Key:         "/business_profile/address/line1",
				Kind:        surface.KindString,
				Description: "Primary address line, such as a street address or PO Box.",
			},
			{
				Name:        "business-profile-address-line2",
				In:          surface.InBody,
				Key:         "/business_profile/address/line2",
				Kind:        surface.KindString,
				Description: "Secondary address line, such as an apartment, suite, unit, or building.",
			},
			{
				Name:        "business-profile-address-postal-code",
				In:          surface.InBody,
				Key:         "/business_profile/address/postal_code",
				Kind:        surface.KindString,
				Description: "Postal or ZIP code.",
			},
			{
				Name:        "business-profile-address-state",
				In:          surface.InBody,
				Key:         "/business_profile/address/state",
				Kind:        surface.KindString,
				Description: "Two-letter state code.",
			},
			{
				Name:        "business-profile-description",
				In:          surface.InBody,
				Key:         "/business_profile/description",
				Kind:        surface.KindString,
				Description: "Description of the business and its products or services.",
			},
			{
				Name:        "business-profile-industry-category",
				In:          surface.InBody,
				Key:         "/business_profile/industry/category",
				Kind:        surface.KindString,
				Description: "Industry category.",
			},
			{
				Name:        "business-profile-industry-mcc",
				In:          surface.InBody,
				Key:         "/business_profile/industry/mcc",
				Kind:        surface.KindString,
				Description: "Merchant category code (MCC) that best describes the business.",
			},
			{
				Name:        "business-profile-industry-sector",
				In:          surface.InBody,
				Key:         "/business_profile/industry/sector",
				Kind:        surface.KindString,
				Description: "Business sector.",
			},
			{
				Name:        "business-profile-legal-name",
				In:          surface.InBody,
				Key:         "/business_profile/legal_name",
				Kind:        surface.KindString,
				Description: "The official registered name of the business.",
			},
			{
				Name:        "business-profile-name",
				In:          surface.InBody,
				Key:         "/business_profile/name",
				Kind:        surface.KindString,
				Required:    true,
				Description: "The operating or trade name of the business.",
			},
			{
				Name:        "business-profile-phone",
				In:          surface.InBody,
				Key:         "/business_profile/phone",
				Kind:        surface.KindString,
				Description: "Primary business phone number in E.164 format.",
			},
			{
				Name:        "business-profile-support-channels-email",
				In:          surface.InBody,
				Key:         "/business_profile/support_channels/email",
				Kind:        surface.KindString,
				Description: "Email address for customer support.",
				Format:      "email",
			},
			{
				Name:        "business-profile-support-channels-phone",
				In:          surface.InBody,
				Key:         "/business_profile/support_channels/phone",
				Kind:        surface.KindString,
				Description: "Customer support phone number in E.164 format.",
			},
			{
				Name:        "business-profile-support-channels-url",
				In:          surface.InBody,
				Key:         "/business_profile/support_channels/url",
				Kind:        surface.KindString,
				Description: "URL of the business's customer support page or contact form.",
				Format:      "uri",
			},
			{
				Name:        "business-profile-tax-id",
				In:          surface.InBody,
				Key:         "/business_profile/tax_id",
				Kind:        surface.KindString,
				Description: "Business tax identification number, such as a US Employer Identification Number (EIN).",
			},
			{
				Name:        "business-profile-use-case",
				In:          surface.InBody,
				Key:         "/business_profile/use_case",
				Kind:        surface.KindString,
				Description: "How the business plans to use Straddle.",
			},
			{
				Name:        "business-profile-website",
				In:          surface.InBody,
				Key:         "/business_profile/website",
				Kind:        surface.KindString,
				Required:    true,
				Description: "URL of the business's primary website.",
				Format:      "uri",
			},
			{
				Name:        "external-id",
				In:          surface.InBody,
				Key:         "/external_id",
				Kind:        surface.KindString,
				Description: "Your unique ID for the account.",
			},
			{
				Name:        "metadata",
				In:          surface.InBody,
				Key:         "/metadata",
				Kind:        surface.KindJSON,
				Description: "Up to 20 user-defined key-value pairs.",
			},
			{
				Name:        "organization-id",
				In:          surface.InBody,
				Key:         "/organization_id",
				Kind:        surface.KindString,
				Required:    true,
				Description: "ID of the organization that will own the account.",
				Format:      "uuid",
			},
		},
		HasBody:              true,
		BodyRequired:         true,
		AcceptsAccountHeader: false,
		ReadOnly:             false,
	}
	cmd := &cobra.Command{
		Use:     "create",
		Short:   "Create an account",
		Example: "  straddle accounts create",
		Annotations: map[string]string{
			"straddle:endpoint":     "accounts.create",
			"straddle:operation-id": "createAccount",
			"straddle:method":       "POST",
			"straddle:path":         "/v1/accounts",
		},
	}
	bind := bindSurface(cmd, flags, s)
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req, err := bind(args)
		if err != nil {
			return err
		}
		return executeSurface(cmd, flags, s, req)
	}
	applyOverlay("accounts.create", cmd)
	return cmd
}
