// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.

package cli

var endpointParents = map[string]string{
	"account-settings.get":                                  "",
	"accounts.create":                                       "accounts",
	"accounts.get":                                          "accounts",
	"accounts.list":                                         "accounts",
	"accounts.onboard":                                      "accounts onboard",
	"accounts.simulate-account-onboarding":                  "accounts simulate",
	"accounts.update":                                       "accounts",
	"bridge.create-bank-account-paykey":                     "bridge",
	"bridge.create-bridge-token":                            "bridge",
	"bridge.create-plaid-paykey":                            "bridge",
	"bridge.create-quiltt-paykey":                           "bridge",
	"capability-requests.create":                            "accounts capability-requests",
	"capability-requests.list":                              "accounts capability-requests",
	"charges.cancel":                                        "charges cancel",
	"charges.create":                                        "charges",
	"charges.get":                                           "charges",
	"charges.get-unmasked-charge":                           "charges unmask",
	"charges.hold":                                          "charges hold",
	"charges.refund":                                        "charges",
	"charges.release":                                       "charges release",
	"charges.resubmit":                                      "charges resubmit",
	"charges.update":                                        "charges",
	"customers.create":                                      "customers",
	"customers.delete":                                      "customers",
	"customers.get":                                         "customers",
	"customers.get-customer-review":                         "customers review",
	"customers.get-unmasked-customer":                       "customers unmasked",
	"customers.list":                                        "customers",
	"customers.refresh-customer-review":                     "customers refresh-review",
	"customers.set-customer-verification-decision":          "customers review",
	"customers.update":                                      "customers",
	"funding-events.get":                                    "funding-events",
	"funding-events.list":                                   "funding-events",
	"funding-events.list-funding-event-payments":            "",
	"funding-events.simulate":                               "funding-events",
	"linked-bank-accounts.cancel":                           "linked-bank-accounts cancel",
	"linked-bank-accounts.create":                           "linked-bank-accounts",
	"linked-bank-accounts.get":                              "linked-bank-accounts",
	"linked-bank-accounts.get-unmasked-linked-bank-account": "linked-bank-accounts unmask",
	"linked-bank-accounts.list":                             "linked-bank-accounts",
	"linked-bank-accounts.update":                           "linked-bank-accounts",
	"organizations.create":                                  "organizations",
	"organizations.get":                                     "organizations",
	"organizations.list":                                    "organizations",
	"paykeys.cancel":                                        "paykeys cancel",
	"paykeys.get":                                           "paykeys",
	"paykeys.get-paykey-review":                             "paykeys review",
	"paykeys.get-unmasked-paykey":                           "paykeys unmasked",
	"paykeys.list":                                          "paykeys",
	"paykeys.refresh-paykey-balance":                        "paykeys refresh-balance",
	"paykeys.refresh-paykey-review":                         "paykeys refresh-review",
	"paykeys.reveal":                                        "paykeys reveal",
	"paykeys.set-paykey-verification-decision":              "paykeys review",
	"paykeys.unblock-paykey":                                "paykeys unblock",
	"payments.list":                                         "",
	"payouts.cancel":                                        "payouts cancel",
	"payouts.create":                                        "payouts",
	"payouts.get":                                           "payouts",
	"payouts.get-unmasked-payout":                           "payouts unmask",
	"payouts.hold":                                          "payouts hold",
	"payouts.release":                                       "payouts release",
	"payouts.resubmit":                                      "payouts resubmit",
	"payouts.update":                                        "payouts",
	"representatives.create":                                "representatives",
	"representatives.get":                                   "representatives",
	"representatives.get-unmasked-representative":           "representatives unmask",
	"representatives.list":                                  "representatives",
	"representatives.update":                                "representatives",
}

var endpointUses = map[string]string{
	"account-settings.get":                                  "account-settings <account_id>",
	"accounts.onboard":                                      "account <account_id>",
	"accounts.simulate-account-onboarding":                  "create <account_id>",
	"bridge.create-bridge-token":                            "create-token",
	"bridge.create-quiltt-paykey":                           "create",
	"charges.cancel":                                        "charge <id>",
	"charges.get-unmasked-charge":                           "charges-v1-get <id>",
	"charges.hold":                                          "charge <id>",
	"charges.release":                                       "charge <id>",
	"charges.resubmit":                                      "create <id>",
	"customers.get-customer-review":                         "get-customer <id>",
	"customers.get-unmasked-customer":                       "get-customer <id>",
	"customers.refresh-customer-review":                     "update <id>",
	"customers.set-customer-verification-decision":          "update-customer <id>",
	"funding-events.list-funding-event-payments":            "funding-event-payments <id>",
	"funding-events.simulate":                               "create",
	"linked-bank-accounts.cancel":                           "update <linked_bank_account_id>",
	"linked-bank-accounts.get-unmasked-linked-bank-account": "get-linked-bank-account-unmasked <linked_bank_account_id>",
	"organizations.get":                                     "get-by-id <organization_id>",
	"paykeys.cancel":                                        "update <id>",
	"paykeys.get-paykey-review":                             "get <id>",
	"paykeys.get-unmasked-paykey":                           "get-paykey <id>",
	"paykeys.refresh-paykey-balance":                        "update <id>",
	"paykeys.refresh-paykey-review":                         "update <id>",
	"paykeys.reveal":                                        "get <id>",
	"paykeys.set-paykey-verification-decision":              "update <id>",
	"paykeys.unblock-paykey":                                "update <id>",
	"payments.list":                                         "payments",
	"payouts.cancel":                                        "payout <id>",
	"payouts.get-unmasked-payout":                           "payouts-v1-get <id>",
	"payouts.hold":                                          "payout <id>",
	"payouts.release":                                       "payout <id>",
	"payouts.resubmit":                                      "create <id>",
	"representatives.get-unmasked-representative":           "get <representative_id>",
}
