// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.

package cli

import (
	"github.com/spf13/cobra"
	"github.com/straddle-build/straddle-cli/internal/surface"
)

func init() {
	registerGeneratedEndpoint("customers.list", newCustomersListCmd)
	registerSurface(surface.Surface{
		Endpoint:    "customers.list",
		OperationID: "listCustomers",
		Method:      "GET",
		Path:        "/v1/customers",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "created-from",
				In:          surface.InQuery,
				Key:         "created_from",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Start date for filtering by `created_at` date.",
				Format:      "date-time",
			},
			{
				Name:        "created-to",
				In:          surface.InQuery,
				Key:         "created_to",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "End date for filtering by `created_at` date.",
				Format:      "date-time",
			},
			{
				Name:        "email",
				In:          surface.InQuery,
				Key:         "email",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter customers by `email` address.",
			},
			{
				Name:        "external-id",
				In:          surface.InQuery,
				Key:         "external_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by your system's `external_id`.",
			},
			{
				Name:        "name",
				In:          surface.InQuery,
				Key:         "name",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter customers by `name` (partial match).",
			},
			{
				Name:        "page-number",
				In:          surface.InQuery,
				Key:         "page_number",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Page number for paginated results.",
				Format:      "int32",
				Default:     "1",
			},
			{
				Name:        "page-size",
				In:          surface.InQuery,
				Key:         "page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Number of results per page.",
				Format:      "int32",
				Default:     "100",
			},
			{
				Name:        "search-text",
				In:          surface.InQuery,
				Key:         "search_text",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "General search term to filter customers.",
			},
			{
				Name:        "sort-by",
				In:          surface.InQuery,
				Key:         "sort_by",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"name", "created_at"},
				Description: "Field used to sort the results.",
			},
			{
				Name:        "sort-order",
				In:          surface.InQuery,
				Key:         "sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "status",
				In:          surface.InQuery,
				Key:         "status",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"pending", "review", "verified", "inactive", "rejected"},
				Description: "Filter customers by their current `status`.",
			},
			{
				Name:        "types",
				In:          surface.InQuery,
				Key:         "types",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"individual", "business"},
				Description: "Filter by customer type `individual` or `business`.",
			},
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
		},
		HasBody:              false,
		BodyRequired:         false,
		AcceptsAccountHeader: true,
		ReadOnly:             true,
	})
}

func newCustomersListCmd(flags *rootFlags) *cobra.Command {
	s := surface.Surface{
		Endpoint:    "customers.list",
		OperationID: "listCustomers",
		Method:      "GET",
		Path:        "/v1/customers",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "created-from",
				In:          surface.InQuery,
				Key:         "created_from",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Start date for filtering by `created_at` date.",
				Format:      "date-time",
			},
			{
				Name:        "created-to",
				In:          surface.InQuery,
				Key:         "created_to",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "End date for filtering by `created_at` date.",
				Format:      "date-time",
			},
			{
				Name:        "email",
				In:          surface.InQuery,
				Key:         "email",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter customers by `email` address.",
			},
			{
				Name:        "external-id",
				In:          surface.InQuery,
				Key:         "external_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by your system's `external_id`.",
			},
			{
				Name:        "name",
				In:          surface.InQuery,
				Key:         "name",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter customers by `name` (partial match).",
			},
			{
				Name:        "page-number",
				In:          surface.InQuery,
				Key:         "page_number",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Page number for paginated results.",
				Format:      "int32",
				Default:     "1",
			},
			{
				Name:        "page-size",
				In:          surface.InQuery,
				Key:         "page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Number of results per page.",
				Format:      "int32",
				Default:     "100",
			},
			{
				Name:        "search-text",
				In:          surface.InQuery,
				Key:         "search_text",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "General search term to filter customers.",
			},
			{
				Name:        "sort-by",
				In:          surface.InQuery,
				Key:         "sort_by",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"name", "created_at"},
				Description: "Field used to sort the results.",
			},
			{
				Name:        "sort-order",
				In:          surface.InQuery,
				Key:         "sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "status",
				In:          surface.InQuery,
				Key:         "status",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"pending", "review", "verified", "inactive", "rejected"},
				Description: "Filter customers by their current `status`.",
			},
			{
				Name:        "types",
				In:          surface.InQuery,
				Key:         "types",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"individual", "business"},
				Description: "Filter by customer type `individual` or `business`.",
			},
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
		},
		HasBody:              false,
		BodyRequired:         false,
		AcceptsAccountHeader: true,
		ReadOnly:             true,
	}
	cmd := &cobra.Command{
		Use:     "list",
		Short:   "List customers",
		Example: "  straddle customers list",
		Annotations: map[string]string{
			"straddle:endpoint":     "customers.list",
			"straddle:operation-id": "listCustomers",
			"straddle:method":       "GET",
			"straddle:path":         "/v1/customers",
			"mcp:read-only":         "true",
		},
	}
	bind := bindSurface(cmd, flags, s)
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req, err := bind(args)
		if err != nil {
			return err
		}
		return executeSurface(cmd, flags, s, req)
	}
	applyOverlay("customers.list", cmd)
	return cmd
}
