// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.

package cli

import (
	"github.com/spf13/cobra"
	"github.com/straddle-build/straddle-cli/internal/surface"
)

func init() {
	registerGeneratedEndpoint("funding-events.list", newFundingEventsListCmd)
	registerSurface(surface.Surface{
		Endpoint:    "funding-events.list",
		OperationID: "listFundingEvents",
		Method:      "GET",
		Path:        "/v1/funding_events",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "created-from",
				In:          surface.InQuery,
				Key:         "created_from",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to funding events created on or after this date.",
				Format:      "date",
			},
			{
				Name:        "created-to",
				In:          surface.InQuery,
				Key:         "created_to",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to funding events created on or before this date.",
				Format:      "date",
			},
			{
				Name:        "direction",
				In:          surface.InQuery,
				Key:         "direction",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"deposit", "withdrawal"},
				Description: "Filter by transfer direction relative to the linked bank account.",
			},
			{
				Name:        "event-type",
				In:          surface.InQuery,
				Key:         "event_type",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"charge_deposit", "charge_reversal", "payout_return", "payout_withdrawal"},
				Description: "Filter by funding event type.",
			},
			{
				Name:        "page-number",
				In:          surface.InQuery,
				Key:         "page_number",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Results page number.",
				Format:      "int32",
				Default:     "1",
			},
			{
				Name:        "page-size",
				In:          surface.InQuery,
				Key:         "page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Results page size.",
				Format:      "int32",
				Default:     "100",
			},
			{
				Name:        "search-text",
				In:          surface.InQuery,
				Key:         "search_text",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Free-text search across funding event fields.",
			},
			{
				Name:        "sort-by",
				In:          surface.InQuery,
				Key:         "sort_by",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"transfer_date", "id", "amount"},
				Description: "Field used to sort the results.",
				Default:     "id",
			},
			{
				Name:        "sort-order",
				In:          surface.InQuery,
				Key:         "sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "status",
				In:          surface.InQuery,
				Key:         "status",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"created", "scheduled", "failed", "cancelled", "on_hold", "pending", "paid", "reversed", "validating"},
				Description: "Filter by funding event status.",
			},
			{
				Name:        "status-reason",
				In:          surface.InQuery,
				Key:         "status_reason",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"insufficient_funds", "closed_bank_account", "invalid_bank_account", "invalid_routing", "disputed", "payment_stopped", "owner_deceased", "frozen_bank_account", "risk_review", "fraudulent", "duplicate_entry", "invalid_paykey", "payment_blocked", "amount_too_large", "too_many_attempts", "internal_system_error", "user_request", "ok", "other_network_return", "payout_refused", "cancel_request", "failed_verification", "require_review", "blocked_by_system", "watchtower_review", "validating", "auto_hold"},
				Description: "Filter by the reason for the most recent status change.",
			},
			{
				Name:        "status-source",
				In:          surface.InQuery,
				Key:         "status_source",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"watchtower", "bank_decline", "customer_dispute", "user_action", "system"},
				Description: "Filter by the source of the most recent status change.",
			},
			{
				Name:        "trace-id",
				In:          surface.InQuery,
				Key:         "trace_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by a network-level trace identifier assigned during processing.",
			},
			{
				Name:        "trace-number",
				In:          surface.InQuery,
				Key:         "trace_number",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by a network trace number assigned during processing.",
			},
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
		},
		HasBody:              false,
		BodyRequired:         false,
		AcceptsAccountHeader: true,
		ReadOnly:             true,
	})
}

func newFundingEventsListCmd(flags *rootFlags) *cobra.Command {
	s := surface.Surface{
		Endpoint:    "funding-events.list",
		OperationID: "listFundingEvents",
		Method:      "GET",
		Path:        "/v1/funding_events",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "created-from",
				In:          surface.InQuery,
				Key:         "created_from",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to funding events created on or after this date.",
				Format:      "date",
			},
			{
				Name:        "created-to",
				In:          surface.InQuery,
				Key:         "created_to",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to funding events created on or before this date.",
				Format:      "date",
			},
			{
				Name:        "direction",
				In:          surface.InQuery,
				Key:         "direction",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"deposit", "withdrawal"},
				Description: "Filter by transfer direction relative to the linked bank account.",
			},
			{
				Name:        "event-type",
				In:          surface.InQuery,
				Key:         "event_type",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"charge_deposit", "charge_reversal", "payout_return", "payout_withdrawal"},
				Description: "Filter by funding event type.",
			},
			{
				Name:        "page-number",
				In:          surface.InQuery,
				Key:         "page_number",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Results page number.",
				Format:      "int32",
				Default:     "1",
			},
			{
				Name:        "page-size",
				In:          surface.InQuery,
				Key:         "page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Results page size.",
				Format:      "int32",
				Default:     "100",
			},
			{
				Name:        "search-text",
				In:          surface.InQuery,
				Key:         "search_text",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Free-text search across funding event fields.",
			},
			{
				Name:        "sort-by",
				In:          surface.InQuery,
				Key:         "sort_by",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"transfer_date", "id", "amount"},
				Description: "Field used to sort the results.",
				Default:     "id",
			},
			{
				Name:        "sort-order",
				In:          surface.InQuery,
				Key:         "sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "status",
				In:          surface.InQuery,
				Key:         "status",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"created", "scheduled", "failed", "cancelled", "on_hold", "pending", "paid", "reversed", "validating"},
				Description: "Filter by funding event status.",
			},
			{
				Name:        "status-reason",
				In:          surface.InQuery,
				Key:         "status_reason",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"insufficient_funds", "closed_bank_account", "invalid_bank_account", "invalid_routing", "disputed", "payment_stopped", "owner_deceased", "frozen_bank_account", "risk_review", "fraudulent", "duplicate_entry", "invalid_paykey", "payment_blocked", "amount_too_large", "too_many_attempts", "internal_system_error", "user_request", "ok", "other_network_return", "payout_refused", "cancel_request", "failed_verification", "require_review", "blocked_by_system", "watchtower_review", "validating", "auto_hold"},
				Description: "Filter by the reason for the most recent status change.",
			},
			{
				Name:        "status-source",
				In:          surface.InQuery,
				Key:         "status_source",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"watchtower", "bank_decline", "customer_dispute", "user_action", "system"},
				Description: "Filter by the source of the most recent status change.",
			},
			{
				Name:        "trace-id",
				In:          surface.InQuery,
				Key:         "trace_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by a network-level trace identifier assigned during processing.",
			},
			{
				Name:        "trace-number",
				In:          surface.InQuery,
				Key:         "trace_number",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by a network trace number assigned during processing.",
			},
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
		},
		HasBody:              false,
		BodyRequired:         false,
		AcceptsAccountHeader: true,
		ReadOnly:             true,
	}
	cmd := &cobra.Command{
		Use:     "list",
		Short:   "List funding events",
		Example: "  straddle funding-events list",
		Annotations: map[string]string{
			"straddle:endpoint":     "funding-events.list",
			"straddle:operation-id": "listFundingEvents",
			"straddle:method":       "GET",
			"straddle:path":         "/v1/funding_events",
			"mcp:read-only":         "true",
		},
	}
	bind := bindSurface(cmd, flags, s)
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req, err := bind(args)
		if err != nil {
			return err
		}
		return executeSurface(cmd, flags, s, req)
	}
	applyOverlay("funding-events.list", cmd)
	return cmd
}
