// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.

package cli

import (
	"github.com/spf13/cobra"
	"github.com/straddle-build/straddle-cli/internal/surface"
)

func init() {
	registerGeneratedEndpoint("paykeys.list", newPaykeysListCmd)
	registerSurface(surface.Surface{
		Endpoint:    "paykeys.list",
		OperationID: "listPaykeys",
		Method:      "GET",
		Path:        "/v1/paykeys",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "created-from",
				In:          surface.InQuery,
				Key:         "created_from",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Start date for filtering by creation date.",
				Format:      "date-time",
			},
			{
				Name:        "created-to",
				In:          surface.InQuery,
				Key:         "created_to",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "End date for filtering by creation date.",
				Format:      "date-time",
			},
			{
				Name:        "customer-id",
				In:          surface.InQuery,
				Key:         "customer_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter paykeys by related customer ID.",
				Format:      "uuid",
			},
			{
				Name:        "page-number",
				In:          surface.InQuery,
				Key:         "page_number",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Page number for paginated results.",
				Format:      "int32",
				Default:     "1",
			},
			{
				Name:        "page-size",
				In:          surface.InQuery,
				Key:         "page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Number of results per page.",
				Format:      "int32",
				Default:     "100",
			},
			{
				Name:        "search-text",
				In:          surface.InQuery,
				Key:         "search_text",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "General search term to filter paykeys.",
			},
			{
				Name:        "sort-by",
				In:          surface.InQuery,
				Key:         "sort_by",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"institution_name", "expires_at", "created_at"},
				Description: "Field used to sort the results.",
			},
			{
				Name:        "sort-order",
				In:          surface.InQuery,
				Key:         "sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "source",
				In:          surface.InQuery,
				Key:         "source",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"bank_account", "straddle", "mx", "plaid", "tan", "quiltt"},
				Description: "Filter paykeys by their source.",
			},
			{
				Name:        "status",
				In:          surface.InQuery,
				Key:         "status",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"pending", "active", "inactive", "rejected", "review", "blocked"},
				Description: "Filter paykeys by their current status.",
			},
			{
				Name:        "unblock-eligible",
				In:          surface.InQuery,
				Key:         "unblock_eligible",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filters paykeys by unblock eligibility.",
			},
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
		},
		HasBody:              false,
		BodyRequired:         false,
		AcceptsAccountHeader: true,
		ReadOnly:             true,
	})
}

func newPaykeysListCmd(flags *rootFlags) *cobra.Command {
	s := surface.Surface{
		Endpoint:    "paykeys.list",
		OperationID: "listPaykeys",
		Method:      "GET",
		Path:        "/v1/paykeys",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "created-from",
				In:          surface.InQuery,
				Key:         "created_from",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Start date for filtering by creation date.",
				Format:      "date-time",
			},
			{
				Name:        "created-to",
				In:          surface.InQuery,
				Key:         "created_to",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "End date for filtering by creation date.",
				Format:      "date-time",
			},
			{
				Name:        "customer-id",
				In:          surface.InQuery,
				Key:         "customer_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter paykeys by related customer ID.",
				Format:      "uuid",
			},
			{
				Name:        "page-number",
				In:          surface.InQuery,
				Key:         "page_number",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Page number for paginated results.",
				Format:      "int32",
				Default:     "1",
			},
			{
				Name:        "page-size",
				In:          surface.InQuery,
				Key:         "page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Number of results per page.",
				Format:      "int32",
				Default:     "100",
			},
			{
				Name:        "search-text",
				In:          surface.InQuery,
				Key:         "search_text",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "General search term to filter paykeys.",
			},
			{
				Name:        "sort-by",
				In:          surface.InQuery,
				Key:         "sort_by",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"institution_name", "expires_at", "created_at"},
				Description: "Field used to sort the results.",
			},
			{
				Name:        "sort-order",
				In:          surface.InQuery,
				Key:         "sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "source",
				In:          surface.InQuery,
				Key:         "source",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"bank_account", "straddle", "mx", "plaid", "tan", "quiltt"},
				Description: "Filter paykeys by their source.",
			},
			{
				Name:        "status",
				In:          surface.InQuery,
				Key:         "status",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"pending", "active", "inactive", "rejected", "review", "blocked"},
				Description: "Filter paykeys by their current status.",
			},
			{
				Name:        "unblock-eligible",
				In:          surface.InQuery,
				Key:         "unblock_eligible",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filters paykeys by unblock eligibility.",
			},
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
		},
		HasBody:              false,
		BodyRequired:         false,
		AcceptsAccountHeader: true,
		ReadOnly:             true,
	}
	cmd := &cobra.Command{
		Use:     "list",
		Short:   "List paykeys",
		Example: "  straddle paykeys list",
		Annotations: map[string]string{
			"straddle:endpoint":     "paykeys.list",
			"straddle:operation-id": "listPaykeys",
			"straddle:method":       "GET",
			"straddle:path":         "/v1/paykeys",
			"mcp:read-only":         "true",
		},
	}
	bind := bindSurface(cmd, flags, s)
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req, err := bind(args)
		if err != nil {
			return err
		}
		return executeSurface(cmd, flags, s, req)
	}
	applyOverlay("paykeys.list", cmd)
	return cmd
}
