// Copyright 2026 hello-keith. Licensed under Apache-2.0. See LICENSE.

package cli

import (
	"github.com/spf13/cobra"
	"github.com/straddle-build/straddle-cli/internal/surface"
)

func init() {
	registerGeneratedEndpoint("payments.list", newPaymentsListCmd)
	registerSurface(surface.Surface{
		Endpoint:    "payments.list",
		OperationID: "listPayments",
		Method:      "GET",
		Path:        "/v1/payments",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "customer-id",
				In:          surface.InQuery,
				Key:         "customer_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the unique identifier of the customer.",
				Format:      "uuid",
			},
			{
				Name:        "default-page-size",
				In:          surface.InQuery,
				Key:         "default_page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Default number of results returned per page.",
				Format:      "int32",
			},
			{
				Name:        "default-sort",
				In:          surface.InQuery,
				Key:         "default_sort",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"created_at", "payment_date", "effective_at", "id", "amount", "updated_at"},
				Description: "Default field used to sort the results.",
				Default:     "id",
			},
			{
				Name:        "default-sort-order",
				In:          surface.InQuery,
				Key:         "default_sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Default order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "external-id",
				In:          surface.InQuery,
				Key:         "external_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by your external identifier for the payment.",
			},
			{
				Name:        "funding-id",
				In:          surface.InQuery,
				Key:         "funding_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the unique identifier of a funding event.",
				Format:      "uuid",
			},
			{
				Name:        "has-refund",
				In:          surface.InQuery,
				Key:         "has_refund",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter charges by whether an associated payout has refunded them.",
			},
			{
				Name:        "has-resubmit",
				In:          surface.InQuery,
				Key:         "has_resubmit",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter payments by whether they have been resubmitted.",
			},
			{
				Name:        "include-metadata",
				In:          surface.InQuery,
				Key:         "include_metadata",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Whether to include metadata in each returned payment.",
			},
			{
				Name:        "is-refund",
				In:          surface.InQuery,
				Key:         "is_refund",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter payouts by whether they refund an original charge.",
			},
			{
				Name:        "is-resubmit",
				In:          surface.InQuery,
				Key:         "is_resubmit",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter payments by whether they resubmit an original payment.",
			},
			{
				Name:        "max-amount",
				In:          surface.InQuery,
				Key:         "max_amount",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments with an amount in cents less than or equal to this value.",
				Format:      "int32",
			},
			{
				Name:        "max-created-at",
				In:          surface.InQuery,
				Key:         "max_created_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments created at or before this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "max-effective-at",
				In:          surface.InQuery,
				Key:         "max_effective_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments effective at or before this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "max-payment-date",
				In:          surface.InQuery,
				Key:         "max_payment_date",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments with a payment date on or before this date.",
				Format:      "date",
			},
			{
				Name:        "max-updated-at",
				In:          surface.InQuery,
				Key:         "max_updated_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments last updated on or before this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "min-amount",
				In:          surface.InQuery,
				Key:         "min_amount",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments with an amount in cents greater than or equal to this value.",
				Format:      "int32",
			},
			{
				Name:        "min-created-at",
				In:          surface.InQuery,
				Key:         "min_created_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments created at or after this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "min-effective-at",
				In:          surface.InQuery,
				Key:         "min_effective_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments effective at or after this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "min-payment-date",
				In:          surface.InQuery,
				Key:         "min_payment_date",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments with a payment date on or after this date.",
				Format:      "date",
			},
			{
				Name:        "min-updated-at",
				In:          surface.InQuery,
				Key:         "min_updated_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments last updated on or after this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "page-number",
				In:          surface.InQuery,
				Key:         "page_number",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Page number to return.",
				Format:      "int32",
				Default:     "1",
			},
			{
				Name:        "page-size",
				In:          surface.InQuery,
				Key:         "page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Number of results to return per page.",
				Format:      "int32",
				Default:     "100",
			},
			{
				Name:        "paykey",
				In:          surface.InQuery,
				Key:         "paykey",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the paykey token.",
			},
			{
				Name:        "paykey-id",
				In:          surface.InQuery,
				Key:         "paykey_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the unique identifier of the paykey.",
				Format:      "uuid",
			},
			{
				Name:        "payment-id",
				In:          surface.InQuery,
				Key:         "payment_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the payment's unique identifier.",
				Format:      "uuid",
			},
			{
				Name:        "payment-status",
				In:          surface.InQuery,
				Key:         "payment_status",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"created", "scheduled", "failed", "cancelled", "on_hold", "pending", "paid", "reversed", "validating"},
				Description: "Filter by payment status.",
			},
			{
				Name:        "payment-type",
				In:          surface.InQuery,
				Key:         "payment_type",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"charge", "payout"},
				Description: "Filter by payment type.",
			},
			{
				Name:        "search-text",
				In:          surface.InQuery,
				Key:         "search_text",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Free-text search across payment fields.",
			},
			{
				Name:        "sort-by",
				In:          surface.InQuery,
				Key:         "sort_by",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"created_at", "payment_date", "effective_at", "id", "amount", "updated_at"},
				Description: "Field used to sort the results.",
				Default:     "id",
			},
			{
				Name:        "sort-order",
				In:          surface.InQuery,
				Key:         "sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "status-reason",
				In:          surface.InQuery,
				Key:         "status_reason",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"insufficient_funds", "closed_bank_account", "invalid_bank_account", "invalid_routing", "disputed", "payment_stopped", "owner_deceased", "frozen_bank_account", "risk_review", "fraudulent", "duplicate_entry", "invalid_paykey", "payment_blocked", "amount_too_large", "too_many_attempts", "internal_system_error", "user_request", "ok", "other_network_return", "payout_refused", "cancel_request", "failed_verification", "require_review", "blocked_by_system", "watchtower_review", "validating", "auto_hold"},
				Description: "Filter by the reason for the most recent payment status change.",
			},
			{
				Name:        "status-source",
				In:          surface.InQuery,
				Key:         "status_source",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"watchtower", "bank_decline", "customer_dispute", "user_action", "system"},
				Description: "Filter by the source of the most recent payment status change.",
			},
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
		},
		HasBody:              false,
		BodyRequired:         false,
		AcceptsAccountHeader: true,
		ReadOnly:             true,
	})
}

func newPaymentsListCmd(flags *rootFlags) *cobra.Command {
	s := surface.Surface{
		Endpoint:    "payments.list",
		OperationID: "listPayments",
		Method:      "GET",
		Path:        "/v1/payments",
		PathParams:  []string{},
		Flags: []surface.Flag{
			{
				Name:        "customer-id",
				In:          surface.InQuery,
				Key:         "customer_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the unique identifier of the customer.",
				Format:      "uuid",
			},
			{
				Name:        "default-page-size",
				In:          surface.InQuery,
				Key:         "default_page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Default number of results returned per page.",
				Format:      "int32",
			},
			{
				Name:        "default-sort",
				In:          surface.InQuery,
				Key:         "default_sort",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"created_at", "payment_date", "effective_at", "id", "amount", "updated_at"},
				Description: "Default field used to sort the results.",
				Default:     "id",
			},
			{
				Name:        "default-sort-order",
				In:          surface.InQuery,
				Key:         "default_sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Default order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "external-id",
				In:          surface.InQuery,
				Key:         "external_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by your external identifier for the payment.",
			},
			{
				Name:        "funding-id",
				In:          surface.InQuery,
				Key:         "funding_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the unique identifier of a funding event.",
				Format:      "uuid",
			},
			{
				Name:        "has-refund",
				In:          surface.InQuery,
				Key:         "has_refund",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter charges by whether an associated payout has refunded them.",
			},
			{
				Name:        "has-resubmit",
				In:          surface.InQuery,
				Key:         "has_resubmit",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter payments by whether they have been resubmitted.",
			},
			{
				Name:        "include-metadata",
				In:          surface.InQuery,
				Key:         "include_metadata",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Whether to include metadata in each returned payment.",
			},
			{
				Name:        "is-refund",
				In:          surface.InQuery,
				Key:         "is_refund",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter payouts by whether they refund an original charge.",
			},
			{
				Name:        "is-resubmit",
				In:          surface.InQuery,
				Key:         "is_resubmit",
				Kind:        surface.KindBoolean,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter payments by whether they resubmit an original payment.",
			},
			{
				Name:        "max-amount",
				In:          surface.InQuery,
				Key:         "max_amount",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments with an amount in cents less than or equal to this value.",
				Format:      "int32",
			},
			{
				Name:        "max-created-at",
				In:          surface.InQuery,
				Key:         "max_created_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments created at or before this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "max-effective-at",
				In:          surface.InQuery,
				Key:         "max_effective_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments effective at or before this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "max-payment-date",
				In:          surface.InQuery,
				Key:         "max_payment_date",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments with a payment date on or before this date.",
				Format:      "date",
			},
			{
				Name:        "max-updated-at",
				In:          surface.InQuery,
				Key:         "max_updated_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments last updated on or before this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "min-amount",
				In:          surface.InQuery,
				Key:         "min_amount",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments with an amount in cents greater than or equal to this value.",
				Format:      "int32",
			},
			{
				Name:        "min-created-at",
				In:          surface.InQuery,
				Key:         "min_created_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments created at or after this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "min-effective-at",
				In:          surface.InQuery,
				Key:         "min_effective_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments effective at or after this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "min-payment-date",
				In:          surface.InQuery,
				Key:         "min_payment_date",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments with a payment date on or after this date.",
				Format:      "date",
			},
			{
				Name:        "min-updated-at",
				In:          surface.InQuery,
				Key:         "min_updated_at",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter to payments last updated on or after this timestamp.",
				Format:      "date-time",
			},
			{
				Name:        "page-number",
				In:          surface.InQuery,
				Key:         "page_number",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Page number to return.",
				Format:      "int32",
				Default:     "1",
			},
			{
				Name:        "page-size",
				In:          surface.InQuery,
				Key:         "page_size",
				Kind:        surface.KindInteger,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Number of results to return per page.",
				Format:      "int32",
				Default:     "100",
			},
			{
				Name:        "paykey",
				In:          surface.InQuery,
				Key:         "paykey",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the paykey token.",
			},
			{
				Name:        "paykey-id",
				In:          surface.InQuery,
				Key:         "paykey_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the unique identifier of the paykey.",
				Format:      "uuid",
			},
			{
				Name:        "payment-id",
				In:          surface.InQuery,
				Key:         "payment_id",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Filter by the payment's unique identifier.",
				Format:      "uuid",
			},
			{
				Name:        "payment-status",
				In:          surface.InQuery,
				Key:         "payment_status",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"created", "scheduled", "failed", "cancelled", "on_hold", "pending", "paid", "reversed", "validating"},
				Description: "Filter by payment status.",
			},
			{
				Name:        "payment-type",
				In:          surface.InQuery,
				Key:         "payment_type",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"charge", "payout"},
				Description: "Filter by payment type.",
			},
			{
				Name:        "search-text",
				In:          surface.InQuery,
				Key:         "search_text",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Description: "Free-text search across payment fields.",
			},
			{
				Name:        "sort-by",
				In:          surface.InQuery,
				Key:         "sort_by",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"created_at", "payment_date", "effective_at", "id", "amount", "updated_at"},
				Description: "Field used to sort the results.",
				Default:     "id",
			},
			{
				Name:        "sort-order",
				In:          surface.InQuery,
				Key:         "sort_order",
				Kind:        surface.KindString,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"asc", "desc"},
				Description: "Order in which to sort the results.",
				Default:     "asc",
			},
			{
				Name:        "status-reason",
				In:          surface.InQuery,
				Key:         "status_reason",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"insufficient_funds", "closed_bank_account", "invalid_bank_account", "invalid_routing", "disputed", "payment_stopped", "owner_deceased", "frozen_bank_account", "risk_review", "fraudulent", "duplicate_entry", "invalid_paykey", "payment_blocked", "amount_too_large", "too_many_attempts", "internal_system_error", "user_request", "ok", "other_network_return", "payout_refused", "cancel_request", "failed_verification", "require_review", "blocked_by_system", "watchtower_review", "validating", "auto_hold"},
				Description: "Filter by the reason for the most recent payment status change.",
			},
			{
				Name:        "status-source",
				In:          surface.InQuery,
				Key:         "status_source",
				Kind:        surface.KindString,
				Array:       true,
				Style:       surface.StyleForm,
				Explode:     true,
				Enum:        []string{"watchtower", "bank_decline", "customer_dispute", "user_action", "system"},
				Description: "Filter by the source of the most recent payment status change.",
			},
			{
				Name:        "correlation-id",
				In:          surface.InHeader,
				Key:         "Correlation-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing a series of related requests.",
			},
			{
				Name:        "request-id",
				In:          surface.InHeader,
				Key:         "Request-Id",
				Kind:        surface.KindString,
				Style:       surface.StyleSimple,
				Description: "Optional client-generated identifier for tracing one request.",
			},
		},
		HasBody:              false,
		BodyRequired:         false,
		AcceptsAccountHeader: true,
		ReadOnly:             true,
	}
	cmd := &cobra.Command{
		Use:     "list",
		Short:   "List payments",
		Example: "  straddle payments list",
		Annotations: map[string]string{
			"straddle:endpoint":     "payments.list",
			"straddle:operation-id": "listPayments",
			"straddle:method":       "GET",
			"straddle:path":         "/v1/payments",
			"mcp:read-only":         "true",
		},
	}
	bind := bindSurface(cmd, flags, s)
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req, err := bind(args)
		if err != nil {
			return err
		}
		return executeSurface(cmd, flags, s, req)
	}
	applyOverlay("payments.list", cmd)
	return cmd
}
